In [1]:
#Model Import
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [2]:
import numpy as np

In [3]:
corpus = [
    # Positive Reviews

    'This is an excellent movie',
    'The move was fantastic I like it',
    'You should watch it is brilliant',
    'Exceptionally good',
    'Wonderfully directed and executed I like it',
    'Its a fantastic series',
    'Never watched such a brillent movie',
    'It is a Wonderful movie',

    # Negtive Reviews

    "horrible acting",
    'waste of money',
    'pathetic picture',
    'It was very boring',
    'I did not like the movie',
    'The movie was horrible',
    'I will not recommend',
    'The acting is pathetic'
]


In [4]:
sentiments = array([1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0])

In [5]:
#Total number of words in corpus
from nltk.tokenize import word_tokenize

all_words = []
for sent in corpus:
    tokenize_word = word_tokenize(sent)
    for word in tokenize_word:
        all_words.append(word)

In [7]:
len(all_words)

71

In [8]:
unique_words = set(all_words)
print(len(unique_words))

45


In [9]:
vocab_length =50

In [10]:
#One hot encoding, 
embedded_sentences = [one_hot(sent, vocab_length) for sent in corpus]
print(embedded_sentences )

[[13, 24, 40, 33, 12], [21, 21, 44, 25, 2, 18, 49], [8, 27, 21, 49, 24, 15], [12, 35], [20, 5, 41, 9, 2, 18, 49], [22, 16, 25, 26], [42, 12, 38, 16, 17, 12], [49, 24, 16, 11, 12], [8, 26], [13, 48, 41], [37, 15], [49, 44, 12, 14], [2, 15, 4, 18, 21, 12], [21, 12, 44, 8], [2, 25, 4, 43], [21, 26, 24, 37]]


In [12]:
# Finding the lenght of longest sentence, as embedding layer expects each sentence/vector of same size
word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

In [14]:
length_long_sentence

7

In [16]:
#Padding of sentece in order to make each sentence of equal size-->Post padding
padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')
print(padded_sentences)

[[13 24 40 33 12  0  0]
 [21 21 44 25  2 18 49]
 [ 8 27 21 49 24 15  0]
 [12 35  0  0  0  0  0]
 [20  5 41  9  2 18 49]
 [22 16 25 26  0  0  0]
 [42 12 38 16 17 12  0]
 [49 24 16 11 12  0  0]
 [ 8 26  0  0  0  0  0]
 [13 48 41  0  0  0  0]
 [37 15  0  0  0  0  0]
 [49 44 12 14  0  0  0]
 [ 2 15  4 18 21 12  0]
 [21 12 44  8  0  0  0]
 [ 2 25  4 43  0  0  0]
 [21 26 24 37  0  0  0]]


In [17]:
#model creation
model = Sequential()
model.add(Embedding(vocab_length, 20, input_length=length_long_sentence))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))  #Binary classification, hence used sigmoid

In [18]:
#model Compilation
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 7, 20)             1000      
_________________________________________________________________
flatten (Flatten)            (None, 140)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 141       
Total params: 1,141
Trainable params: 1,141
Non-trainable params: 0
_________________________________________________________________
None


In [19]:
# Model Fitting
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 0s 30ms/step - loss: 0.6912 - acc: 0.6875
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6878 - acc: 0.6875
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6845 - acc: 0.8125
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6811 - acc: 0.8750
Epoch 5/100
1/1 [==============================] - 0s 997us/step - loss: 0.6778 - acc: 0.9375
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6744 - acc: 0.9375
Epoch 7/100
1/1 [==============================] - 0s 997us/step - loss: 0.6711 - acc: 0.9375
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6677 - acc: 0.8750
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6644 - acc: 0.8750
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6611 - acc: 0.8750
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.

1/1 [==============================] - 0s 2ms/step - loss: 0.3254 - acc: 1.0000
Epoch 89/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3211 - acc: 1.0000
Epoch 90/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3168 - acc: 1.0000
Epoch 91/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3126 - acc: 1.0000
Epoch 92/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3084 - acc: 1.0000
Epoch 93/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3042 - acc: 1.0000
Epoch 94/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3001 - acc: 1.0000
Epoch 95/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2961 - acc: 1.0000
Epoch 96/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2920 - acc: 1.0000
Epoch 97/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2880 - acc: 1.0000
Epoch 98/100
1/1 [==============================] - 0s 997us/step - loss: 0.2841 - 

In [20]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


In [21]:
# Word Embedding Using Pretarined Model

In [23]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [24]:
word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(corpus)

In [40]:
word_tokenizer

In [25]:
#to get the vocab lenght, wordindex attribute is used on word_tokenizer
vocab_length = len(word_tokenizer.word_index) + 1

In [26]:
embedded_sentences = word_tokenizer.texts_to_sequences(corpus)
print(embedded_sentences)

[[14, 3, 15, 16, 1], [4, 17, 6, 9, 5, 7, 2], [18, 19, 20, 2, 3, 21], [22, 23], [24, 25, 26, 27, 5, 7, 2], [28, 8, 9, 29], [30, 31, 32, 8, 33, 1], [2, 3, 8, 34, 1], [10, 11], [35, 36, 37], [12, 38], [2, 6, 39, 40], [5, 41, 13, 7, 4, 1], [4, 1, 6, 10], [5, 42, 13, 43], [4, 11, 3, 12]]


In [27]:
from nltk.tokenize import word_tokenize

word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')

print(padded_sentences)

[[14  3 15 16  1  0  0]
 [ 4 17  6  9  5  7  2]
 [18 19 20  2  3 21  0]
 [22 23  0  0  0  0  0]
 [24 25 26 27  5  7  2]
 [28  8  9 29  0  0  0]
 [30 31 32  8 33  1  0]
 [ 2  3  8 34  1  0  0]
 [10 11  0  0  0  0  0]
 [35 36 37  0  0  0  0]
 [12 38  0  0  0  0  0]
 [ 2  6 39 40  0  0  0]
 [ 5 41 13  7  4  1  0]
 [ 4  1  6 10  0  0  0]
 [ 5 42 13 43  0  0  0]
 [ 4 11  3 12  0  0  0]]


In [30]:
from numpy import array
from numpy import asarray
from numpy import zeros

embeddings_dictionary = dict()
glove_file = open('./glove.6B/glove.6B.100d.txt', encoding="utf8")

In [31]:
glove_file

<_io.TextIOWrapper name='./glove.6B/glove.6B.100d.txt' mode='r' encoding='utf8'>

In [32]:
#creating dictionary as words as key and 100dim vectors as values
for line in glove_file:
    records = line.split()
    word = records[0]
    vector_dimensions = asarray(records[1:], dtype='float32')
    embeddings_dictionary [word] = vector_dimensions

glove_file.close()

In [34]:
embeddings_dictionary['the']

array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
       -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
        0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
       -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
        0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
       -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
        0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
        0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
       -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
       -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
       -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
       -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
       -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
       -1.2526  ,  0.071624,  0.70565 ,  0.49744 , 

In [35]:
embedding_matrix = zeros((vocab_length, 100))
for word, index in word_tokenizer.word_index.items():
    embedding_vector = embeddings_dictionary.get(word)
    if embedding_vector is not None:
        embedding_matrix[index] = embedding_vector

In [ ]:
#Now embedding matrix contains the pretained word embedding for the words in our corpus

In [36]:
model = Sequential()
embedding_layer = Embedding(vocab_length, 100, weights=[embedding_matrix], input_length=length_long_sentence, trainable=False)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [37]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 7, 100)            4400      
_________________________________________________________________
flatten_1 (Flatten)          (None, 700)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 701       
Total params: 5,101
Trainable params: 701
Non-trainable params: 4,400
_________________________________________________________________
None


In [38]:
model.fit(padded_sentences, sentiments, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6473 - acc: 0.6875
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6235 - acc: 0.6875
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6007 - acc: 0.8125
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5789 - acc: 0.8125
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5580 - acc: 0.8125
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5379 - acc: 0.8750
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5187 - acc: 1.0000
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5002 - acc: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 997us/step - loss: 0.4826 - acc: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4657 - acc: 1.0000
Epoch 11/100
1/1 [==============================] - 0s 998us/step - loss: 0.4

1/1 [==============================] - 0s 2ms/step - loss: 0.0735 - acc: 1.0000
Epoch 89/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0725 - acc: 1.0000
Epoch 90/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0714 - acc: 1.0000
Epoch 91/100
1/1 [==============================] - 0s 997us/step - loss: 0.0704 - acc: 1.0000
Epoch 92/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0694 - acc: 1.0000
Epoch 93/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0685 - acc: 1.0000
Epoch 94/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0676 - acc: 1.0000
Epoch 95/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0666 - acc: 1.0000
Epoch 96/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0657 - acc: 1.0000
Epoch 97/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0649 - acc: 1.0000
Epoch 98/100
1/1 [==============================] - 0s 997us/step - loss: 0.0640 

In [39]:
loss, accuracy = model.evaluate(padded_sentences, sentiments, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000
